import './globals.css';
import { Inter } from 'next/font/google';
import ClientLayout from './clientlayout';
import SmoothScrollWrapper from './Components/smoothscroll'; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
    
        <ClientLayout>{children}</ClientLayout>
      
      </body>
    </html>
  );
}
